CREATE TABLE EMPLOYEES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FORENAME TEXT,
    SURNAME TEXT,
    PASSWORD TEXT
)

CREATE TABLE WORK_DAY_PROFILES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    BREAK BOOLEAN,
    BREAK_TIME INTEGER
)

CREATE TABLE SHIFT_PROFILES (
    ID INTEGER,
    START DATETIME,
    END DATETIME,
    WORK_DAY_PROFILE_ID INTEGER,
    FOREIGN KEY(WORK_DAY_PROFILE_ID) REFERENCES WORK_DAY_PROFILES(ID) ON DELETE CASCADE
)

CREATE TABLE WORK_DAYS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DAT DATE,
    TARGET REAL,
    ACTUAL REAL,
    OVERTIME REAL,
    BREAK BOOLEAN,
    BREAK_TIME INTEGER,
    WORK_MONTH_ID INTEGER,
    FOREIGN KEY(WORK_MONTH_ID) REFERENCES WORK_MONTH(ID) ON DELETE RESTRICT
)

CREATE TABLE WORK_MONTH (
    ID INTEGER,
    MONTH INTEGER,
    YEAR INTEGER,
    TARGET REAL,
    ACTUAL REAL,
    OVERTIME REAL,
    EMPLOYEE_ID INTEGER,
    FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(ID) ON DELETE RESTRICT
)

CREATE TABLE SHIFTS (
    ID INTEGER,
    START DATETIME,
    END DATETIME,
    WORK_DAY_ID INTEGER,
    FOREIGN KEY(WORK_DAY_ID) REFERENCES WORK_DAYS(ID) ON DELETE CASCADE
)

CREATE TABLE CALCULATION_PERIOD (
    ID INTEGER,
    START_DATE DATE,
    END_DATE DATE,
    MONDAY_PROFILE_ID INTEGER,
    TUESDAY_PROFILE_ID INTEGER,
    WEDNESDAY_PROFILE_ID INTEGER,
    THURSDAY_PROFILE_ID INTEGER,
    FRIDAY_PROFILE_ID INTEGER,
    SATURDAY_PROFILE_ID INTEGER,
    SUNDAY_PROFILE_ID INTEGER,
    EMPLOYEE_ID INTEGER,
    FOREIGN KEY(MONDAY_PROFILE_ID) REFERENCES WORK_DAY_PROFILES(ID) ON DELETE CASCADE,
    FOREIGN KEY(TUESDAY_PROFILE_ID) REFERENCES WORK_DAY_PROFILES(ID) ON DELETE CASCADE,
    FOREIGN KEY(WEDNESDAY_PROFILE_ID) REFERENCES WORK_DAY_PROFILES(ID) ON DELETE CASCADE,
    FOREIGN KEY(THURSDAY_PROFILE_ID) REFERENCES WORK_DAY_PROFILES(ID) ON DELETE CASCADE,
    FOREIGN KEY(FRIDAY_PROFILE_ID) REFERENCES WORK_DAY_PROFILES(ID) ON DELETE CASCADE,
    FOREIGN KEY(SATURDAY_PROFILE_ID) REFERENCES WORK_DAY_PROFILES(ID) ON DELETE CASCADE,
    FOREIGN KEY(SUNDAY_PROFILE_ID) REFERENCES WORK_DAY_PROFILES(ID) ON DELETE CASCADE,
    FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(ID) ON DELETE CASCADE,
)

CREATE TABLE ADMIN (
    PASSWORD TEXT
)